'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18331
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18331.
'
Namespace pay
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18331"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="easyrtgsSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class easyrtgs
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private creditCollectionAcctOperationCompleted As System.Threading.SendOrPostCallback
        
        Private creditCollectionAcct2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private creditCollectionAcct3OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.easiRTGSBatch.My.MySettings.Default.easiRTGSBatch_pay_easyrtgs
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event creditCollectionAcctCompleted As creditCollectionAcctCompletedEventHandler
        
        '''<remarks/>
        Public Event creditCollectionAcct2Completed As creditCollectionAcct2CompletedEventHandler
        
        '''<remarks/>
        Public Event creditCollectionAcct3Completed As creditCollectionAcct3CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/creditCollectionAcct", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function creditCollectionAcct(ByVal xml As String) As String
            Dim results() As Object = Me.Invoke("creditCollectionAcct", New Object() {xml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub creditCollectionAcctAsync(ByVal xml As String)
            Me.creditCollectionAcctAsync(xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub creditCollectionAcctAsync(ByVal xml As String, ByVal userState As Object)
            If (Me.creditCollectionAcctOperationCompleted Is Nothing) Then
                Me.creditCollectionAcctOperationCompleted = AddressOf Me.OncreditCollectionAcctOperationCompleted
            End If
            Me.InvokeAsync("creditCollectionAcct", New Object() {xml}, Me.creditCollectionAcctOperationCompleted, userState)
        End Sub
        
        Private Sub OncreditCollectionAcctOperationCompleted(ByVal arg As Object)
            If (Not (Me.creditCollectionAcctCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent creditCollectionAcctCompleted(Me, New creditCollectionAcctCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/creditCollectionAcct2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function creditCollectionAcct2(ByVal xml As String, ByVal docnum As Long) As String
            Dim results() As Object = Me.Invoke("creditCollectionAcct2", New Object() {xml, docnum})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub creditCollectionAcct2Async(ByVal xml As String, ByVal docnum As Long)
            Me.creditCollectionAcct2Async(xml, docnum, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub creditCollectionAcct2Async(ByVal xml As String, ByVal docnum As Long, ByVal userState As Object)
            If (Me.creditCollectionAcct2OperationCompleted Is Nothing) Then
                Me.creditCollectionAcct2OperationCompleted = AddressOf Me.OncreditCollectionAcct2OperationCompleted
            End If
            Me.InvokeAsync("creditCollectionAcct2", New Object() {xml, docnum}, Me.creditCollectionAcct2OperationCompleted, userState)
        End Sub
        
        Private Sub OncreditCollectionAcct2OperationCompleted(ByVal arg As Object)
            If (Not (Me.creditCollectionAcct2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent creditCollectionAcct2Completed(Me, New creditCollectionAcct2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/creditCollectionAcct3", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function creditCollectionAcct3(ByVal xml As String, ByVal docnum As Long) As String
            Dim results() As Object = Me.Invoke("creditCollectionAcct3", New Object() {xml, docnum})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub creditCollectionAcct3Async(ByVal xml As String, ByVal docnum As Long)
            Me.creditCollectionAcct3Async(xml, docnum, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub creditCollectionAcct3Async(ByVal xml As String, ByVal docnum As Long, ByVal userState As Object)
            If (Me.creditCollectionAcct3OperationCompleted Is Nothing) Then
                Me.creditCollectionAcct3OperationCompleted = AddressOf Me.OncreditCollectionAcct3OperationCompleted
            End If
            Me.InvokeAsync("creditCollectionAcct3", New Object() {xml, docnum}, Me.creditCollectionAcct3OperationCompleted, userState)
        End Sub
        
        Private Sub OncreditCollectionAcct3OperationCompleted(ByVal arg As Object)
            If (Not (Me.creditCollectionAcct3CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent creditCollectionAcct3Completed(Me, New creditCollectionAcct3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18331")>  _
    Public Delegate Sub creditCollectionAcctCompletedEventHandler(ByVal sender As Object, ByVal e As creditCollectionAcctCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18331"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class creditCollectionAcctCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18331")>  _
    Public Delegate Sub creditCollectionAcct2CompletedEventHandler(ByVal sender As Object, ByVal e As creditCollectionAcct2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18331"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class creditCollectionAcct2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18331")>  _
    Public Delegate Sub creditCollectionAcct3CompletedEventHandler(ByVal sender As Object, ByVal e As creditCollectionAcct3CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18331"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class creditCollectionAcct3CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
